spring.application.name=microservicio-estadistica
server.port = 8005
#server.port = 8025
spring.datasource.url=jdbc:mysql://localhost:3306/estadistica_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.showsql=true

spring.jpa.properties.hibernate.format_sql=true
